import type { Metadata } from "next";
import "./globals.css";
import { NotesProvider } from "@/contexts/NotesContext";
import { CssBaseline } from "@mui/material";
import { PopupProvider } from "@/contexts/PopupContext";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<CssBaseline />
				<NotesProvider>
					<PopupProvider>{children}</PopupProvider>
				</NotesProvider>
			</body>
		</html>
	);
}
